// web/src/views/PermissionsView.vue
<template>
  <div class="font-sans space-y-6 text-white max-w-[1400px] mx-auto py-8">
    
    <!-- Visual Title Header (Matches Image 5) -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/[0.08] pb-6">
      <div>
        <h1 class="font-display text-2xl md:text-3xl font-bold text-white tracking-wide">
          Cybersecurity Permissions Console
        </h1>
        <p class="text-xs text-slate-400 font-mono uppercase tracking-wider mt-1 flex items-center gap-2">
          <span class="w-1.5 h-1.5 rounded-full bg-neon-purple animate-pulse"></span>
          Virtual Guard Node: <span class="text-neon-purple">ACTIVE-WG-09</span>
        </p>
      </div>

      <!-- Neon Cyan "Add Member" Button (Image 5) -->
      <button
        @click="handleAdd"
        class="self-start sm:self-center px-4.5 py-2 rounded-xl bg-cyan-400 text-slate-950 font-display font-bold text-xs tracking-wider transition-all hover:bg-neon-cyan hover:shadow-[0_0_15px_rgba(0,240,255,0.4)] active:scale-95 cursor-pointer flex items-center gap-1.5"
      >
        <span class="material-symbols-outlined text-[18px]">person_add</span>
        <span>Add {{ currentTabName }}</span>
      </button>
    </div>

    <!-- Segmented Controller navigation tabs (Image 5) -->
    <div class="flex items-center space-x-1 border-b border-white/[0.05]">
      <button
        @click="activeTab = 'members'; refreshData()"
        :class="[
          'py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer',
          activeTab === 'members' ? 'border-neon-cyan text-neon-cyan font-bold' : 'border-transparent text-slate-400 hover:text-white'
        ]"
      >
        Space Members
      </button>
      <button
        @click="activeTab = 'roles'; refreshData()"
        :class="[
          'py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer',
          activeTab === 'roles' ? 'border-neon-cyan text-neon-cyan font-bold' : 'border-transparent text-slate-400 hover:text-white'
        ]"
      >
        Roles
      </button>
      <button
        @click="activeTab = 'policies'; refreshData()"
        :class="[
          'py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer',
          activeTab === 'policies' ? 'border-neon-cyan text-neon-cyan font-bold' : 'border-transparent text-slate-400 hover:text-white'
        ]"
      >
        Policies
      </button>
    </div>

    <!-- Space Members Tab (Matches screenshot 5 layout) -->
    <div v-if="activeTab === 'members'" class="space-y-4">
      
      <!-- Member Search filter -->
      <div class="relative max-w-sm">
        <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[16px] text-slate-500">search</span>
        <input
          type="text"
          placeholder="Filter members by name..."
          v-model="searchTerm"
          class="w-full text-xs text-white pl-9 pr-4 py-2 rounded-xl border border-white/[0.08] bg-slate-950/80 focus:border-neon-cyan focus:outline-none placeholder:text-slate-500"
        />
      </div>

      <!-- Members Grid/List Panel -->
      <div class="cyber-panel rounded-2xl overflow-hidden border border-white/[0.06] shadow-xl" v-loading="loading">
        <div class="overflow-x-auto">
          <table class="w-full text-left border-collapse min-w-[650px]">
            <thead>
              <tr class="border-b border-white/[0.08] bg-slate-950/40 text-[10px] font-mono uppercase text-slate-400 tracking-wider">
                <th class="py-3.5 px-4.5">Username</th>
                <th class="py-3.5 px-4.5">Display Name</th>
                <th class="py-3.5 px-4.5">Roles</th>
                <th class="py-3.5 px-4.5">Status</th>
                <th class="py-3.5 px-4.5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-white/[0.05] text-xs">
              <tr
                v-for="m in filteredMembers"
                :key="m.id"
                class="hover:bg-white/[0.015] transition-colors group relative"
              >
                <!-- Active border row highlight -->
                <td class="py-4.5 px-4.5 font-mono text-neon-cyan font-semibold">
                  {{ m.username }}
                </td>

                <td class="py-4.5 px-4.5 text-slate-200">
                  {{ m.displayName || m.username }}
                </td>

                <!-- Role Pill badges -->
                <td class="py-4.5 px-4.5">
                  <div class="flex flex-wrap gap-1.5">
                    <span
                      class="px-2 py-0.5 rounded text-[10px] font-mono border"
                      :class="
                        m.role === 'ADMIN'
                          ? 'border-indigo-500/35 text-indigo-400 bg-indigo-950/15'
                          : m.role === 'KNOWLEDGE_ADMIN'
                          ? 'border-cyan-500/30 text-cyan-400 bg-cyan-950/15'
                          : 'border-slate-500/25 text-slate-400 bg-slate-950/20'
                      "
                    >
                      {{ m.role || 'VIEWER' }}
                    </span>
                  </div>
                </td>

                <!-- Active/Inactive status with dynamic bullet animation -->
                <td class="py-4.5 px-4.5">
                  <span class="flex items-center gap-1.5 font-mono">
                    <span
                      class="w-2 h-2 rounded-full"
                      :class="
                        m.status === 'ACTIVE'
                          ? 'bg-emerald-500 shadow-[0_0_8px_#10b981] animate-pulse'
                          : 'bg-red-500 shadow-[0_0_8px_#ef4444]'
                      "
                    ></span>
                    <span :class="m.status === 'ACTIVE' ? 'text-emerald-400' : 'text-red-400'">
                      {{ m.status === 'ACTIVE' ? 'Active' : 'Inactive' }}
                    </span>
                  </span>
                </td>

                <!-- Edit/Remove buttons -->
                <td class="py-4.5 px-4.5 text-right font-mono">
                  <div class="flex items-center justify-end space-x-2">
                    <button
                      class="px-2.5 py-1 rounded border border-white/[0.06] hover:border-cyan-500/40 text-slate-450 hover:text-white transition-all text-[10px] cursor-pointer"
                    >
                      Edit
                    </button>
                    <button
                      class="px-2.5 py-1 rounded border border-red-950/40 hover:border-red-500 text-red-500 hover:text-red-400 hover:bg-red-950/15 transition-all text-[10px] cursor-pointer"
                    >
                      Remove
                    </button>
                  </div>
                </td>
              </tr>
              <tr v-if="filteredMembers.length === 0">
                <td colspan="5" class="py-8 text-center text-slate-500 font-mono text-xs">
                  No members found matching "{{ searchTerm }}"
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Pagination controls -->
        <div class="bg-slate-950/40 px-6 py-4 border-t border-white/[0.05] flex items-center justify-between text-xs font-mono text-slate-500">
          <span>Showing 1-{{ filteredMembers.length }} of {{ filteredMembers.length }}</span>
          <div class="flex items-center space-x-1.5">
            <button class="px-2.5 py-1 rounded bg-cyan-950/40 text-neon-cyan border border-neon-cyan/30">1</button>
            <button class="px-2.5 py-1.5 rounded text-[10px] hover:text-white transition-all flex items-center gap-0.5 cursor-pointer">
              <span>Next</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Roles & Polices tab visual mockups -->
    <div v-if="activeTab === 'roles'" class="grid grid-cols-1 md:grid-cols-3 gap-6" v-loading="loading">
      <div v-for="role in roles" :key="role.id" class="cyber-panel rounded-2xl p-6 border-white/[0.06] relative">
        <h3 class="text-sm font-mono uppercase font-semibold mb-2" :class="role.isSystem ? 'text-neon-cyan' : 'text-slate-200'">{{ role.name }}</h3>
        <p class="text-slate-350 text-xs leading-relaxed mb-4">
          {{ role.description || 'Custom role with defined policy attachments.' }}
        </p>
        <div class="flex justify-between items-center mt-4">
          <span class="text-[10px] font-mono text-slate-500">{{ role.memberCount || 0 }} members assigned</span>
          <button v-if="!role.isSystem" @click="handleDeleteRole(role.id)" class="text-[10px] font-mono text-red-500 hover:text-red-400 transition-colors cursor-pointer">Delete</button>
        </div>
      </div>
    </div>

    <div v-if="activeTab === 'policies'" class="space-y-4" v-loading="loading">
      <div v-for="policy in policies" :key="policy.id" class="cyber-panel rounded-2xl p-6 border-white/[0.06] flex items-center justify-between">
        <div>
          <h3 class="text-xs font-mono uppercase tracking-wider text-white font-bold mb-1">{{ policy.name }}</h3>
          <p class="text-slate-400 text-xs mt-1">Resource: {{ policy.resource }}</p>
          <div class="flex gap-2 mt-2">
            <span v-for="action in policy.actions" :key="action" class="text-[9px] font-mono text-slate-500 border border-slate-700/50 bg-slate-800/30 px-1.5 py-0.5 rounded">
              {{ action }}
            </span>
          </div>
        </div>
        <span class="px-2.5 py-1 rounded bg-emerald-950/45 text-emerald-400 font-mono text-[9px] font-bold border border-emerald-500/20 uppercase tracking-widest">
          {{ policy.isSystem ? 'SYSTEM' : 'CUSTOM' }}
        </span>
      </div>
    </div>

    <!-- Modals -->
    <!-- Add Member Modal -->
    <div v-if="memberModalVisible" class="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
      <div class="bg-slate-900 border border-white/10 rounded-2xl max-w-md w-full p-6 md:p-8 shadow-2xl relative">
        <h2 class="font-display text-xl font-bold text-white mb-4 flex items-center gap-2">
          <span class="material-symbols-outlined text-cyan-400 text-[20px]">person_add</span>
          <span>Add Member to Virtual Space</span>
        </h2>
        
        <form @submit.prevent="submitMember" class="space-y-4">
          <div>
            <label class="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
              Username
            </label>
            <input
              type="text"
              v-model="memberForm.username"
              placeholder="e.g. alice.wonder"
              class="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none font-mono"
              required
            />
          </div>

          <div>
            <label class="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-2">
              Assign Cyber Roles
            </label>
            <select
              v-model="memberForm.roleId"
              class="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none font-mono"
              required
            >
              <option value="" disabled>Select a role...</option>
              <option v-for="r in roles" :key="r.id" :value="r.id">{{ r.name }}</option>
            </select>
          </div>

          <div class="flex items-center justify-end space-x-3 pt-4">
            <button
              type="button"
              @click="memberModalVisible = false"
              class="px-4 py-2 rounded-xl border border-white/[0.08] text-xs font-mono text-slate-400 hover:text-white tracking-wider cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="submitting"
              class="px-4 py-2 rounded-xl cyber-btn-cyan text-xs font-mono tracking-wider cursor-pointer disabled:opacity-50"
            >
              Authorize Unit
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Add Role Modal -->
    <div v-if="roleModalVisible" class="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
      <div class="bg-slate-900 border border-white/10 rounded-2xl max-w-md w-full p-6 md:p-8 shadow-2xl relative">
        <h2 class="font-display text-xl font-bold text-white mb-4 flex items-center gap-2">
          <span class="material-symbols-outlined text-cyan-400 text-[20px]">badge</span>
          <span>Create Custom Role</span>
        </h2>
        
        <form @submit.prevent="submitRole" class="space-y-4">
          <div>
            <label class="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
              Role Name
            </label>
            <input
              type="text"
              v-model="roleForm.name"
              placeholder="e.g. External Auditor"
              class="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none font-mono"
              required
            />
          </div>

          <div>
            <label class="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
              Role Description
            </label>
            <textarea
              v-model="roleForm.description"
              placeholder="Briefly describe the purpose of this role"
              rows="3"
              class="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none font-mono"
            ></textarea>
          </div>

          <div class="flex items-center justify-end space-x-3 pt-4">
            <button
              type="button"
              @click="roleModalVisible = false"
              class="px-4 py-2 rounded-xl border border-white/[0.08] text-xs font-mono text-slate-400 hover:text-white tracking-wider cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              :disabled="submitting"
              class="px-4 py-2 rounded-xl cyber-btn-cyan text-xs font-mono tracking-wider cursor-pointer disabled:opacity-50"
            >
              Confirm Creation
            </button>
          </div>
        </form>
      </div>
    </div>

  </div>
</template>

<script setup lang="ts">
import { ElMessage, ElMessageBox } from 'element-plus'
import { ref, computed, onMounted } from 'vue'
import { getRoles, getMembers, getPolicies, createRole, addMember, deleteRole, type Role, type Member, type Policy } from '@/api/permissions'

defineOptions({
  name: 'PermissionsView',
})

const activeTab = ref('members')
const searchTerm = ref('')
const loading = ref(false)
const submitting = ref(false)

const members = ref<Member[]>([])
const roles = ref<Role[]>([])
const policies = ref<Policy[]>([])

const currentTabName = computed(() => {
  if (activeTab.value === 'members') return 'Member'
  if (activeTab.value === 'roles') return 'Role'
  return 'Policy'
})

const filteredMembers = computed(() => {
  if (!searchTerm.value) return members.value
  const term = searchTerm.value.toLowerCase()
  return members.value.filter(m => 
    m.username.toLowerCase().includes(term) || 
    (m.displayName && m.displayName.toLowerCase().includes(term))
  )
})

// Modals
const roleModalVisible = ref(false)
const roleForm = ref({ name: '', description: '' })

const memberModalVisible = ref(false)
const memberForm = ref({ username: '', roleId: '' })

const loadData = async () => {
  loading.value = true
  try {
    if (activeTab.value === 'members') {
      members.value = await getMembers()
    } else if (activeTab.value === 'roles') {
      roles.value = await getRoles()
    } else if (activeTab.value === 'policies') {
      policies.value = await getPolicies()
    }
  } catch (err: any) {
    ElMessage.error(err.message || '加载失败')
  } finally {
    loading.value = false
  }
}

const refreshData = () => {
  loadData()
}

// Global initialization
onMounted(async () => {
  // Preload roles so member modal has options
  roles.value = await getRoles()
  loadData()
})

const handleAdd = () => {
  if (activeTab.value === 'members') {
    memberForm.value = { username: '', roleId: '' }
    memberModalVisible.value = true
  } else if (activeTab.value === 'roles') {
    roleForm.value = { name: '', description: '' }
    roleModalVisible.value = true
  } else {
    ElMessage.info('暂不支持通过界面直接新增策略')
  }
}

const submitRole = async () => {
  if (!roleForm.value.name) return
  submitting.value = true
  try {
    await createRole(roleForm.value)
    ElMessage.success('角色创建成功')
    roleModalVisible.value = false
    refreshData()
  } catch (err: any) {
    ElMessage.error(err.message || '创建失败')
  } finally {
    submitting.value = false
  }
}

const submitMember = async () => {
  if (!memberForm.value.username || !memberForm.value.roleId) return
  submitting.value = true
  try {
    await addMember(memberForm.value)
    ElMessage.success('成员添加成功')
    memberModalVisible.value = false
    refreshData()
  } catch (err: any) {
    ElMessage.error(err.message || '添加失败，请确认用户存在')
  } finally {
    submitting.value = false
  }
}

const handleDeleteRole = async (roleId: string) => {
  try {
    await ElMessageBox.confirm('确定要删除此角色吗？', '警告', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      confirmButtonClass: 'el-button--danger'
    })
    
    await deleteRole(roleId)
    ElMessage.success('删除成功')
    refreshData()
  } catch (err: any) {
    if (err !== 'cancel') {
      ElMessage.error(err.message || '删除失败')
    }
  }
}
</script>

// sticth/update0620/html-ui-hotlinker/src/components/PermissionsView.tsx
import React, { useState } from 'react';
import { Shield, ShieldAlert, Plus, Search, Trash2, Edit2, CheckCircle2, UserPlus, FileText, Lock, Users } from 'lucide-react';
import { TeamMember } from '../types';

interface PermissionsViewProps {
  members: TeamMember[];
  onAddMember: (member: Omit<TeamMember, 'id'>) => void;
  onUpdateMember: (member: TeamMember) => void;
  onRemoveMember: (memberId: string) => void;
}

export default function PermissionsView({
  members,
  onAddMember,
  onUpdateMember,
  onRemoveMember,
}: PermissionsViewProps) {
  const [activeTab, setActiveTab] = useState<'members' | 'roles' | 'policies'>('members');
  const [searchTerm, setSearchTerm] = useState('');
  
  // New Member Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newUsername, setNewUsername] = useState('');
  const [newDisplayName, setNewDisplayName] = useState('');
  const [useAdmin, setUseAdmin] = useState(false);
  const [useEditor, setUseEditor] = useState(false);
  const [useViewer, setUseViewer] = useState(true);

  // Edit Member Modal State
  const [editingMember, setEditingMember] = useState<TeamMember | null>(null);

  const filteredMembers = members.filter(
    (m) =>
      m.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
      m.displayName.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleCreateMemberSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newUsername.trim() || !newDisplayName.trim()) return;

    const roles: ('Admin' | 'Content Editor' | 'Viewer')[] = [];
    if (useAdmin) roles.push('Admin');
    if (useEditor) roles.push('Content Editor');
    if (useViewer) roles.push('Viewer');

    if (roles.length === 0) roles.push('Viewer');

    onAddMember({
      username: newUsername.trim().toLowerCase(),
      displayName: newDisplayName.trim(),
      roles,
      status: 'Active',
    });

    setNewUsername('');
    setNewDisplayName('');
    setUseAdmin(false);
    setUseEditor(false);
    setUseViewer(true);
    setIsModalOpen(false);
  };

  const handleEditMemberSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingMember) return;
    onUpdateMember(editingMember);
    setEditingMember(null);
  };

  return (
    <div className="font-sans space-y-6">
      
      {/* Visual Title Header (Matches Image 5) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/[0.08] pb-6">
        <div>
          <h1 className="font-display text-2xl md:text-3xl font-bold text-white tracking-wide">
            Cybersecurity Permissions Console
          </h1>
          <p className="text-xs text-slate-400 font-mono uppercase tracking-wider mt-1 flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-neon-purple animate-pulse"></span>
            Virtual Guard Node: <span className="text-neon-purple">ACTIVE-WG-09</span>
          </p>
        </div>

        {/* Neon Cyan "Add Member" Button (Image 5) */}
        <button
          onClick={() => setIsModalOpen(true)}
          className="self-start sm:self-center px-4.5 py-2 rounded-xl bg-cyan-400 text-slate-950 font-display font-bold text-xs tracking-wider transition-all hover:bg-neon-cyan hover:shadow-[0_0_15px_rgba(0,240,255,0.4)] active:scale-95 cursor-pointer flex items-center gap-1.5"
        >
          <UserPlus className="w-4.5 h-4.5" />
          <span>Add Member</span>
        </button>
      </div>

      {/* Segmented Controller navigation tabs (Image 5) */}
      <div className="flex items-center space-x-1 border-b border-white/[0.05]">
        <button
          onClick={() => setActiveTab('members')}
          className={`py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer ${
            activeTab === 'members'
              ? 'border-neon-cyan text-neon-cyan font-bold'
              : 'border-transparent text-slate-400 hover:text-white'
          }`}
        >
          Space Members
        </button>
        <button
          onClick={() => setActiveTab('roles')}
          className={`py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer ${
            activeTab === 'roles'
              ? 'border-neon-cyan text-neon-cyan font-bold'
              : 'border-transparent text-slate-400 hover:text-white'
          }`}
        >
          Roles
        </button>
        <button
          onClick={() => setActiveTab('policies')}
          className={`py-3 px-4.5 text-xs font-mono tracking-wider transition-all relative border-b-2 cursor-pointer ${
            activeTab === 'policies'
              ? 'border-neon-cyan text-neon-cyan font-bold'
              : 'border-transparent text-slate-400 hover:text-white'
          }`}
        >
          Policies
        </button>
      </div>

      {/* Space Members Tab (Matches screenshot 5 layout) */}
      {activeTab === 'members' && (
        <div className="space-y-4">
          
          {/* Member Search filter */}
          <div className="relative max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
            <input
              type="text"
              placeholder="Filter members by name..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full text-xs text-white pl-9 pr-4 py-2 rounded-xl border border-white/[0.08] bg-slate-950/80 focus:border-neon-cyan focus:outline-none placeholder:text-slate-500"
            />
          </div>

          {/* Members Grid/List Panel */}
          <div className="cyber-panel rounded-2xl overflow-hidden border border-white/[0.06] shadow-xl">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse min-w-[650px]">
                <thead>
                  <tr className="border-b border-white/[0.08] bg-slate-950/40 text-[10px] font-mono uppercase text-slate-400 tracking-wider">
                    <th className="py-3.5 px-4.5">Username</th>
                    <th className="py-3.5 px-4.5">Display Name</th>
                    <th className="py-3.5 px-4.5">Roles</th>
                    <th className="py-3.5 px-4.5">Status</th>
                    <th className="py-3.5 px-4.5 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.05] text-xs">
                  {filteredMembers.map((m) => (
                    <tr
                      key={m.id}
                      className="hover:bg-white/[0.015] transition-colors group relative"
                    >
                      {/* Active border row highlight - matches selection in screenshot 5 */}
                      <td className="py-4.5 px-4.5 font-mono text-neon-cyan font-semibold">
                        {m.username}
                      </td>

                      <td className="py-4.5 px-4.5 text-slate-200">
                        {m.displayName}
                      </td>

                      {/* Role Pill badges formatted inside turquoise outline/badges */}
                      <td className="py-4.5 px-4.5">
                        <div className="flex flex-wrap gap-1.5">
                          {m.roles.map((role) => (
                            <span
                              key={role}
                              className={`px-2 py-0.5 rounded text-[10px] font-mono border ${
                                role === 'Admin'
                                  ? 'border-indigo-500/35 text-indigo-400 bg-indigo-950/15'
                                  : role === 'Content Editor'
                                  ? 'border-cyan-500/30 text-cyan-400 bg-cyan-950/15'
                                  : 'border-slate-500/25 text-slate-400 bg-slate-950/20'
                              }`}
                            >
                              {role}
                            </span>
                          ))}
                        </div>
                      </td>

                      {/* Active/Inactive status with dynamic bullet animation */}
                      <td className="py-4.5 px-4.5">
                        <span className="flex items-center gap-1.5 font-mono">
                          <span
                            className={`w-2 h-2 rounded-full ${
                              m.status === 'Active'
                                ? 'bg-emerald-500 shadow-[0_0_8px_#10b981] animate-pulse'
                                : 'bg-red-500 shadow-[0_0_8px_#ef4444]'
                            }`}
                          />
                          <span className={m.status === 'Active' ? 'text-emerald-400' : 'text-red-400'}>
                            {m.status}
                          </span>
                        </span>
                      </td>

                      {/* Edit/Remove buttons */}
                      <td className="py-4.5 px-4.5 text-right font-mono">
                        <div className="flex items-center justify-end space-x-2">
                          <button
                            onClick={() => setEditingMember(m)}
                            className="px-2.5 py-1 rounded border border-white/[0.06] hover:border-cyan-500/40 text-slate-450 hover:text-white transition-all text-[10px] cursor-pointer"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => onRemoveMember(m.id)}
                            className="px-2.5 py-1 rounded border border-red-950/40 hover:border-red-500 text-red-500 hover:text-red-400 hover:bg-red-950/15 transition-all text-[10px] cursor-pointer"
                          >
                            Remove
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination controls from Image 5 */}
            <div className="bg-slate-950/40 px-6 py-4 border-t border-white/[0.05] flex items-center justify-between text-xs font-mono text-slate-500">
              <span>Showing 1-{filteredMembers.length} of 25</span>
              <div className="flex items-center space-x-1.5">
                <button className="px-2.5 py-1 rounded bg-cyan-950/40 text-neon-cyan border border-neon-cyan/30">1</button>
                <button className="px-2.5 py-1 rounded hover:bg-slate-800 hover:text-white transition-all">2</button>
                <button className="px-2.5 py-1 rounded hover:bg-slate-800 hover:text-white transition-all">3</button>
                <button className="px-2.5 py-1.5 rounded text-[10px] hover:text-white transition-all flex items-center gap-0.5">
                  <span>Next</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Roles & Polices tab visual mockups */}
      {activeTab === 'roles' && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="cyber-panel rounded-2xl p-6 border-white/[0.06]">
            <h3 className="text-sm font-mono uppercase text-neon-cyan font-semibold mb-2">Admin</h3>
            <p className="text-slate-350 text-xs leading-relaxed mb-4">
              Full administrative override. Capacity to create knowledge directories, configure vector configurations, manage space access, and purge logs.
            </p>
            <span className="text-[10px] font-mono text-slate-500">2 members assigned</span>
          </div>
          <div className="cyber-panel rounded-2xl p-6 border-white/[0.06]">
            <h3 className="text-sm font-mono uppercase text-neon-purple font-semibold mb-2">Content Editor</h3>
            <p className="text-slate-350 text-xs leading-relaxed mb-4">
              Authorized to upload raw files, trigger telemetry ingestion logs, edit document scopes, and initiate embedding runs.
            </p>
            <span className="text-[10px] font-mono text-slate-500">3 members assigned</span>
          </div>
          <div className="cyber-panel rounded-2xl p-6 border-white/[0.06]">
            <h3 className="text-sm font-mono uppercase text-slate-400 font-semibold mb-2">Viewer</h3>
            <p className="text-slate-350 text-xs leading-relaxed mb-4">
              Access limited to executing RAG chats, reading evidence traces, inspecting basic telemetry stats, and checking system health.
            </p>
            <span className="text-[10px] font-mono text-slate-500">20 members assigned</span>
          </div>
        </div>
      )}

      {activeTab === 'policies' && (
        <div className="space-y-4">
          <div className="cyber-panel rounded-2xl p-6 border-white/[0.06] flex items-center justify-between">
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-white font-bold mb-1">Double-Factor Auth Gate</h3>
              <p className="text-slate-400 text-xs">Forced OTP checks before Admin credentials can establish SSH partitions.</p>
            </div>
            <span className="px-2.5 py-1 rounded bg-emerald-950/45 text-emerald-400 font-mono text-[9px] font-bold border border-emerald-500/20 uppercase tracking-widest">ENABLED</span>
          </div>
          <div className="cyber-panel rounded-2xl p-6 border-white/[0.06] flex items-center justify-between">
            <div>
              <h3 className="text-xs font-mono uppercase tracking-wider text-white font-bold mb-1">Vector Anonymization Scrape</h3>
              <p className="text-slate-400 text-xs">Automatically redact PII (SSNs, Phone integers, emails) prior to embedding ingest vectors.</p>
            </div>
            <span className="px-2.5 py-1 rounded bg-amber-950/45 text-amber-400 font-mono text-[9px] font-bold border border-amber-500/20 uppercase tracking-widest">GATING ROUTE</span>
          </div>
        </div>
      )}

      {/* Add Member Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
          <div className="bg-slate-900 border border-white/10 rounded-2xl max-w-md w-full p-6 md:p-8 shadow-2xl relative">
            <h2 className="font-display text-xl font-bold text-white mb-4 flex items-center gap-2">
              <UserPlus className="text-cyan-400 w-5 h-5" />
              <span>Add Member to Virtual Space</span>
            </h2>
            
            <form onSubmit={handleCreateMemberSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
                  Username
                </label>
                <input
                  type="text"
                  value={newUsername}
                  onChange={(e) => setNewUsername(e.target.value)}
                  placeholder="e.g. alice.wonder"
                  className="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none font-mono"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
                  Display Name
                </label>
                <input
                  type="text"
                  value={newDisplayName}
                  onChange={(e) => setNewDisplayName(e.target.value)}
                  placeholder="e.g. Alice Wonder"
                  className="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-2">
                  Assign Cyber Roles
                </label>
                <div className="space-y-2 bg-slate-950/60 p-3 rounded-lg border border-white/[0.05]">
                  <label className="flex items-center space-x-2 text-xs text-slate-300 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={useAdmin}
                      onChange={(e) => setUseAdmin(e.target.checked)}
                      className="rounded text-cyan-500 focus:ring-0 bg-slate-900"
                    />
                    <span>Admin Override</span>
                  </label>
                  <label className="flex items-center space-x-2 text-xs text-slate-300 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={useEditor}
                      onChange={(e) => setUseEditor(e.target.checked)}
                      className="rounded text-cyan-500 focus:ring-0 bg-slate-900"
                    />
                    <span>Content Editor Ingestion</span>
                  </label>
                  <label className="flex items-center space-x-2 text-xs text-slate-300 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={useViewer}
                      onChange={(e) => setUseViewer(e.target.checked)}
                      className="rounded text-cyan-500 focus:ring-0 bg-slate-900"
                    />
                    <span>Viewer</span>
                  </label>
                </div>
              </div>

              <div className="flex items-center justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 rounded-xl border border-white/[0.08] text-xs font-mono text-slate-400 hover:text-white tracking-wider cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl cyber-btn-cyan text-xs font-mono tracking-wider cursor-pointer"
                >
                  Authorize Unit
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Member Modal */}
      {editingMember && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
          <div className="bg-slate-900 border border-white/10 rounded-2xl max-w-md w-full p-6 md:p-8 shadow-2xl relative">
            <h2 className="font-display text-xl font-bold text-white mb-4">Edit Space Member Settings</h2>
            
            <form onSubmit={handleEditMemberSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
                  Display Name
                </label>
                <input
                  type="text"
                  value={editingMember.displayName}
                  onChange={(e) => setEditingMember({ ...editingMember, displayName: e.target.value })}
                  className="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-1000 focus:border-neon-cyan focus:outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-mono uppercase tracking-wider text-slate-400 mb-1">
                  Status
                </label>
                <select
                  value={editingMember.status}
                  onChange={(e) => setEditingMember({ ...editingMember, status: e.target.value as 'Active' | 'Inactive' })}
                  className="w-full text-sm text-white px-4 py-2.5 rounded-xl border border-white/[0.08] bg-slate-950 focus:border-neon-cyan focus:outline-none text-cyan-400 font-mono"
                >
                  <option value="Active">Active Duty</option>
                  <option value="Inactive">Suspended Node</option>
                </select>
              </div>

              <div className="flex items-center justify-end space-x-3 pt-4">
                <button
                  type="button"
                  onClick={() => setEditingMember(null)}
                  className="px-4 py-2 rounded-xl border border-white/[0.08] text-xs font-mono text-slate-400 hover:text-white tracking-wider cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl cyber-btn-cyan text-xs font-mono tracking-wider cursor-pointer"
                >
                  Confirm Policy Changes
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
